-- require("config.theme")
require("config.options")
-- require("config.keymaps")
require("config.remap")
-- require("config.session")
-- require("config.tabline")
-- require("config.diagnostics")
-- require("config.autocmds")
-- require("config.lsp")
