require("plugins.celluralautomation")
require("plugins.cmp")
require("plugins.comment")
-- require("plugins.dashboard")
require("plugins.debugger")
require("plugins.diffview")
require("plugins.fugitive")
require("plugins.gitsigns")
-- require("plugins.harpoon")
require("plugins.lualine")
-- require("plugins.navigator")
require("plugins.nvim-treesitter")
require("plugins.rainbow_delimiters")
require("plugins.smear_cursor")
require("plugins.trouble")
require("plugins.telescope")
require("plugins.theme")
require("plugins.whichkey")
